pipeline {
    agent none
    stages {
        stage('Schedule test-pipeline') {
            when {
              changeset 'build-schedules/test-pipeline'
            }
            steps {
                updateBuildSchedule(jobStr: 'test-pipeline', cronStr: readTrusted('build-schedules/test-pipeline'))
            }
        }
        stage('Schedule test-pipeline-2') {
            when {
              changeset 'build-schedules/test-pipeline-2'
            }
            steps {
                updateBuildSchedule(jobStr: 'test-pipeline-2', cronStr: readTrusted('build-schedules/test-pipeline-2'))
            }
        }
    }
}

